import type { Incident } from "./incidents";

type Seed = Omit<Incident, "verified">;

export const INCIDENT_SEED: Seed[] = [
  {
    id: "our-lady-salvation-baghdad-2010",
    title: "Siege at Our Lady of Salvation",
    siteName: "Our Lady of Salvation Syriac Catholic Cathedral",
    occurredOn: "2010-10-31",
    country: "Iraq",
    countryCode: "IRQ",
    city: "Baghdad",
    region: "Middle East & North Africa",
    latitude: 33.3152,
    longitude: 44.3661,
    incidentType: "siege",
    severity: "critical",
    fatalities: 58,
    injured: 75,
    structuresDamaged: 1,
    denomination: "Syriac Catholic",
    summary:
      "Gunmen from the Islamic State of Iraq stormed Sunday evening Mass, took the congregation hostage, and fought security forces for hours. Fifty-eight people were killed, including two priests and a large number of worshippers.",
    context:
      "The assault was among the deadliest single attacks on Iraqi Christians and accelerated the postwar exodus from Baghdad’s historic churches.",
    sourceName: "BBC / contemporaneous reporting",
    sourceUrl: "https://www.bbc.com/news/world-middle-east-11667722",
    scope: "single",
  },
  {
    id: "st-theresa-madalla-2011",
    title: "Christmas Day bombing at St. Theresa",
    siteName: "St. Theresa Catholic Church",
    occurredOn: "2011-12-25",
    country: "Nigeria",
    countryCode: "NGA",
    city: "Madalla",
    region: "Sub-Saharan Africa",
    latitude: 9.1167,
    longitude: 7.2167,
    incidentType: "bombing",
    severity: "critical",
    fatalities: 37,
    injured: 50,
    structuresDamaged: 1,
    denomination: "Catholic",
    summary:
      "A suicide car bomb detonated as worshippers left Christmas Mass on the outskirts of Abuja. Boko Haram claimed the attack. At least 37 people were killed.",
    context:
      "The bombing was part of a Christmas 2011 wave against Nigerian churches and remains one of the country’s most lethal church attacks.",
    sourceName: "Reuters",
    sourceUrl: "https://www.reuters.com/article/us-nigeria-blast-idUSTRE7BO03320111225",
    scope: "single",
  },
  {
    id: "all-saints-peshawar-2013",
    title: "Suicide bombing at All Saints Church",
    siteName: "All Saints Church",
    occurredOn: "2013-09-22",
    country: "Pakistan",
    countryCode: "PAK",
    city: "Peshawar",
    region: "South Asia",
    latitude: 34.0151,
    longitude: 71.5249,
    incidentType: "bombing",
    severity: "critical",
    fatalities: 127,
    injured: 250,
    structuresDamaged: 1,
    denomination: "Anglican / Church of Pakistan",
    summary:
      "Two suicide bombers struck the congregation as Sunday service ended in the old city. It is the deadliest attack on Pakistani Christians on record, with 127 killed.",
    context:
      "Jundallah, a Pakistani Taliban faction, claimed responsibility. The church stands in Peshawar’s historic Kohati Gate quarter.",
    sourceName: "BBC",
    sourceUrl: "https://www.bbc.com/news/world-asia-24193737",
    scope: "single",
  },
  {
    id: "youhanabad-lahore-2015",
    title: "Twin church bombings in Youhanabad",
    siteName: "St. John’s Catholic Church and Christ Church",
    occurredOn: "2015-03-15",
    country: "Pakistan",
    countryCode: "PAK",
    city: "Lahore",
    region: "South Asia",
    latitude: 31.4312,
    longitude: 74.3173,
    incidentType: "bombing",
    severity: "critical",
    fatalities: 15,
    injured: 70,
    structuresDamaged: 2,
    denomination: "Catholic and Protestant",
    summary:
      "Suicide bombers attacked two churches in Lahore’s largest Christian neighborhood during Sunday services. Jamaat-ul-Ahrar claimed the blasts. Fifteen people were killed.",
    context:
      "Youhanabad is one of Pakistan’s biggest Christian settlements. The bombings triggered days of unrest in the city.",
    sourceName: "Al Jazeera",
    sourceUrl: "https://www.aljazeera.com/news/2015/3/15/deadly-suicide-blasts-hit-pakistan-churches",
    scope: "single",
  },
  {
    id: "emanuel-ame-charleston-2015",
    title: "Massacre at Emanuel AME Church",
    siteName: "Emanuel African Methodist Episcopal Church",
    occurredOn: "2015-06-17",
    country: "United States",
    countryCode: "USA",
    city: "Charleston",
    region: "North America",
    latitude: 32.7875,
    longitude: -79.9331,
    incidentType: "shooting",
    severity: "critical",
    fatalities: 9,
    injured: 1,
    structuresDamaged: 0,
    denomination: "African Methodist Episcopal",
    summary:
      "A white supremacist sat through a Wednesday Bible study, then opened fire on the prayer circle. Nine people were killed, including State Senator Clementa Pinckney, the church’s pastor.",
    context:
      "Mother Emanuel is one of the oldest Black churches in the American South. The attack was prosecuted as a federal hate crime and death-penalty case.",
    sourceName: "Department of Justice",
    sourceUrl: "https://www.justice.gov/opa/pr/federal-jury-sentences-dylann-roof-death",
    scope: "single",
  },
  {
    id: "father-hamel-rouen-2016",
    title: "Murder of Father Jacques Hamel",
    siteName: "Church of Saint-Étienne",
    occurredOn: "2016-07-26",
    country: "France",
    countryCode: "FRA",
    city: "Saint-Étienne-du-Rouvray",
    region: "Europe",
    latitude: 49.3781,
    longitude: 1.1081,
    incidentType: "stabbing",
    severity: "high",
    fatalities: 1,
    injured: 1,
    structuresDamaged: 0,
    denomination: "Catholic",
    summary:
      "Two men pledged to the Islamic State forced an 85-year-old priest to his knees during morning Mass and slit his throat. A worshipper was also critically wounded.",
    context:
      "The killing shocked European churches and is commemorated as a modern martyrdom in the French Catholic Church.",
    sourceName: "BBC",
    sourceUrl: "https://www.bbc.com/news/world-europe-36892785",
    scope: "single",
  },
  {
    id: "botroseya-cairo-2016",
    title: "Botroseya chapel bombing",
    siteName: "St. Peter and St. Paul Church (Botroseya)",
    occurredOn: "2016-12-11",
    country: "Egypt",
    countryCode: "EGY",
    city: "Cairo",
    region: "Middle East & North Africa",
    latitude: 30.0444,
    longitude: 31.2357,
    incidentType: "bombing",
    severity: "critical",
    fatalities: 29,
    injured: 47,
    structuresDamaged: 1,
    denomination: "Coptic Orthodox",
    summary:
      "A suicide bomber detonated inside a chapel adjoining St. Mark’s Cathedral, the Coptic papal seat. Twenty-nine people were killed, most of them women and children at a Sunday service.",
    context:
      "ISIS claimed the bombing. It was the deadliest attack on Copts in Cairo in years and preceded the 2017 Palm Sunday church bombings.",
    sourceName: "Reuters",
    sourceUrl: "https://www.reuters.com/article/us-egypt-blast-idUSKBN1400CY",
    scope: "single",
  },
  {
    id: "tanta-st-george-2017",
    title: "Palm Sunday bombing in Tanta",
    siteName: "St. George’s Coptic Church",
    occurredOn: "2017-04-09",
    country: "Egypt",
    countryCode: "EGY",
    city: "Tanta",
    region: "Middle East & North Africa",
    latitude: 30.7865,
    longitude: 31.0004,
    incidentType: "bombing",
    severity: "critical",
    fatalities: 29,
    injured: 71,
    structuresDamaged: 1,
    denomination: "Coptic Orthodox",
    summary:
      "A bomb exploded in the front pews during Palm Sunday liturgy in the Nile Delta city of Tanta. Twenty-nine worshippers were killed.",
    context:
      "A second ISIS bombing struck St. Mark’s Cathedral in Alexandria hours later. President Sisi declared a three-month state of emergency.",
    sourceName: "BBC",
    sourceUrl: "https://www.bbc.com/news/world-middle-east-39543661",
    scope: "single",
  },
  {
    id: "alexandria-st-mark-2017",
    title: "Palm Sunday bombing at St. Mark’s",
    siteName: "St. Mark’s Coptic Orthodox Cathedral",
    occurredOn: "2017-04-09",
    country: "Egypt",
    countryCode: "EGY",
    city: "Alexandria",
    region: "Middle East & North Africa",
    latitude: 31.2001,
    longitude: 29.9187,
    incidentType: "bombing",
    severity: "critical",
    fatalities: 17,
    injured: 48,
    structuresDamaged: 1,
    denomination: "Coptic Orthodox",
    summary:
      "A suicide bomber detonated at the gate of the historic patriarchal cathedral in Alexandria as Pope Tawadros II finished Palm Sunday liturgy. Seventeen people were killed.",
    context:
      "Paired with the Tanta bombing the same morning, the attacks were the worst single-day assault on Egypt’s Coptic community in modern times.",
    sourceName: "The Guardian",
    sourceUrl: "https://www.theguardian.com/world/2017/apr/09/egypt-coptic-church-bombing-tanta-palm-sunday",
    scope: "single",
  },
  {
    id: "sutherland-springs-2017",
    title: "Shooting at First Baptist Sutherland Springs",
    siteName: "First Baptist Church",
    occurredOn: "2017-11-05",
    country: "United States",
    countryCode: "USA",
    city: "Sutherland Springs",
    region: "North America",
    latitude: 29.2733,
    longitude: -98.0567,
    incidentType: "shooting",
    severity: "critical",
    fatalities: 26,
    injured: 22,
    structuresDamaged: 0,
    denomination: "Baptist",
    summary:
      "A gunman opened fire during Sunday worship in a small Texas sanctuary, killing 26 people — including an unborn child — and wounding 22. It is the deadliest shooting in an American church.",
    context:
      "A neighbor confronted the attacker outside. Subsequent litigation focused on the U.S. Air Force’s failure to report the shooter’s prior conviction to the federal background-check system.",
    sourceName: "Texas Department of Public Safety / AP",
    sourceUrl: "https://apnews.com/article/texas-church-shooting-sutherland-springs",
    scope: "single",
  },
  {
    id: "surabaya-churches-2018",
    title: "Coordinated church bombings in Surabaya",
    siteName: "Santa Maria, Diponegoro GKI, and Surabaya Pusat Pentecostal",
    occurredOn: "2018-05-13",
    country: "Indonesia",
    countryCode: "IDN",
    city: "Surabaya",
    region: "East & Southeast Asia",
    latitude: -7.2575,
    longitude: 112.7521,
    incidentType: "bombing",
    severity: "critical",
    fatalities: 15,
    injured: 40,
    structuresDamaged: 3,
    denomination: "Catholic and Protestant",
    summary:
      "Members of one family linked to Jemaah Ansharut Daulah struck three churches on a Sunday morning with suicide bombs, including a car bomb and an attack involving children. About 15 people were killed at the church sites.",
    context:
      "The Surabaya attacks were Indonesia’s worst bombing in a decade and led to a tightening of the country’s anti-terror law.",
    sourceName: "Reuters",
    sourceUrl: "https://www.reuters.com/article/us-indonesia-blasts-idUSKCN1IE0D1",
    scope: "campaign",
  },
  {
    id: "jolo-cathedral-2019",
    title: "Twin bombings at Jolo Cathedral",
    siteName: "Our Lady of Mount Carmel Cathedral",
    occurredOn: "2019-01-27",
    country: "Philippines",
    countryCode: "PHL",
    city: "Jolo",
    region: "East & Southeast Asia",
    latitude: 6.0522,
    longitude: 121.0022,
    incidentType: "bombing",
    severity: "critical",
    fatalities: 20,
    injured: 102,
    structuresDamaged: 1,
    denomination: "Catholic",
    summary:
      "Two bombs exploded at the cathedral — one inside during Mass, one outside as troops responded. Twenty civilians and security personnel were killed and more than 100 wounded.",
    context:
      "Abu Sayyaf and Jamaah Ansharut Daulah were blamed. The attack came a week after the Bangsamoro autonomy plebiscite.",
    sourceName: "BBC",
    sourceUrl: "https://www.bbc.com/news/world-asia-47018747",
    scope: "single",
  },
  {
    id: "st-anthonys-colombo-2019",
    title: "Easter bombing at St. Anthony’s Shrine",
    siteName: "St. Anthony’s Shrine",
    occurredOn: "2019-04-21",
    country: "Sri Lanka",
    countryCode: "LKA",
    city: "Colombo",
    region: "South Asia",
    latitude: 6.9485,
    longitude: 79.8636,
    incidentType: "bombing",
    severity: "critical",
    fatalities: 53,
    injured: 100,
    structuresDamaged: 1,
    denomination: "Catholic",
    summary:
      "A suicide bomber struck the packed Kochchikade shrine during Easter Sunday Mass, one of three church bombings that morning. Dozens were killed at this site alone.",
    context:
      "The island-wide Easter attacks — churches and hotels — killed 269 people. National Thowheeth Jama’ath carried them out with ISIS inspiration.",
    sourceName: "Reuters / Sri Lanka presidential commission",
    sourceUrl: "https://www.reuters.com/article/us-sri-lanka-blasts-idUSKCN1RX0J4",
    scope: "single",
  },
  {
    id: "st-sebastians-negombo-2019",
    title: "Easter bombing at St. Sebastian’s",
    siteName: "St. Sebastian’s Church",
    occurredOn: "2019-04-21",
    country: "Sri Lanka",
    countryCode: "LKA",
    city: "Negombo",
    region: "South Asia",
    latitude: 7.209,
    longitude: 79.838,
    incidentType: "bombing",
    severity: "critical",
    fatalities: 104,
    injured: 120,
    structuresDamaged: 1,
    denomination: "Catholic",
    summary:
      "The deadliest of the Easter Sunday church bombings tore through Mass in the coastal town of Negombo. More than 100 parishioners were killed.",
    context:
      "Negombo is a majority-Catholic town north of Colombo. The restored church keeps shrapnel-scarred statues as a memorial.",
    sourceName: "The New York Times",
    sourceUrl: "https://www.nytimes.com/2019/04/21/world/asia/sri-lanka-explosions.html",
    scope: "single",
  },
  {
    id: "zion-batticaloa-2019",
    title: "Easter bombing at Zion Church",
    siteName: "Zion Church",
    occurredOn: "2019-04-21",
    country: "Sri Lanka",
    countryCode: "LKA",
    city: "Batticaloa",
    region: "South Asia",
    latitude: 7.7309,
    longitude: 81.6747,
    incidentType: "bombing",
    severity: "critical",
    fatalities: 29,
    injured: 50,
    structuresDamaged: 1,
    denomination: "Evangelical",
    summary:
      "A suicide bomber struck an evangelical Easter service on Sri Lanka’s east coast. Twenty-nine people were killed, many of them children attending Sunday school.",
    context:
      "A church security volunteer stopped the attacker at the gate; the bomb still detonated among arriving families.",
    sourceName: "CNN",
    sourceUrl: "https://www.cnn.com/2019/04/21/asia/sri-lanka-explosions/index.html",
    scope: "single",
  },
  {
    id: "dablo-burkina-2019",
    title: "Mass shooting during Mass in Dablo",
    siteName: "Catholic parish, Dablo",
    occurredOn: "2019-05-12",
    country: "Burkina Faso",
    countryCode: "BFA",
    city: "Dablo",
    region: "Sub-Saharan Africa",
    latitude: 13.0167,
    longitude: -0.5667,
    incidentType: "shooting",
    severity: "high",
    fatalities: 6,
    injured: 0,
    structuresDamaged: 0,
    denomination: "Catholic",
    summary:
      "Armed men interrupted Sunday Mass in Sanmatenga Province, executed Father Siméon Yampa and five parishioners, and burned the church and nearby shops.",
    context:
      "The killing was part of a wider jihadist campaign across Burkina Faso’s north that has emptied parishes and displaced priests.",
    sourceName: "Reuters",
    sourceUrl: "https://www.reuters.com/article/us-burkina-security-idUSKCN1SI0K4",
    scope: "single",
  },
  {
    id: "west-freeway-white-settlement-2019",
    title: "Shooting at West Freeway Church of Christ",
    siteName: "West Freeway Church of Christ",
    occurredOn: "2019-12-29",
    country: "United States",
    countryCode: "USA",
    city: "White Settlement",
    region: "North America",
    latitude: 32.7596,
    longitude: -97.4586,
    incidentType: "shooting",
    severity: "high",
    fatalities: 2,
    injured: 0,
    structuresDamaged: 0,
    denomination: "Church of Christ",
    summary:
      "A gunman opened fire during a Sunday service, killing two congregants. A volunteer member of the church security team shot the attacker within seconds, captured on the livestream.",
    context:
      "The incident is widely cited in U.S. church-security training as both a mass-casualty near-miss and a case study in armed volunteer response.",
    sourceName: "Tarrant County Sheriff / AP",
    sourceUrl: "https://apnews.com/article/texas-church-shooting-white-settlement",
    scope: "single",
  },
  {
    id: "nice-notre-dame-2020",
    title: "Stabbing at Notre-Dame de Nice",
    siteName: "Basilica of Notre-Dame de Nice",
    occurredOn: "2020-10-29",
    country: "France",
    countryCode: "FRA",
    city: "Nice",
    region: "Europe",
    latitude: 43.7034,
    longitude: 7.2663,
    incidentType: "stabbing",
    severity: "high",
    fatalities: 3,
    injured: 0,
    structuresDamaged: 0,
    denomination: "Catholic",
    summary:
      "A man entered the basilica at opening hour and stabbed three Catholic faithful, including a woman whose body was found inside and the sacristan. The attacker was shot and arrested.",
    context:
      "The attack came weeks after the beheading of teacher Samuel Paty and prompted France to raise its national security alert.",
    sourceName: "Reuters",
    sourceUrl: "https://www.reuters.com/article/us-france-security-nice-idUSKBN27E1F0",
    scope: "single",
  },
  {
    id: "managua-cathedral-2020",
    title: "Arson in the Managua cathedral chapel",
    siteName: "Metropolitan Cathedral of the Immaculate Conception",
    occurredOn: "2020-07-31",
    country: "Nicaragua",
    countryCode: "NIC",
    city: "Managua",
    region: "Latin America",
    latitude: 12.1328,
    longitude: -86.2504,
    incidentType: "arson",
    severity: "moderate",
    fatalities: 0,
    injured: 0,
    structuresDamaged: 1,
    denomination: "Catholic",
    summary:
      "An attacker threw a firebomb into the chapel of the Blood of Christ, nearly destroying a revered crucifix. No one was killed.",
    context:
      "The arson came amid a wider confrontation between the Ortega government and the Catholic Church, which later saw Bishop Rolando Álvarez imprisoned and priests expelled.",
    sourceName: "Reuters",
    sourceUrl: "https://www.reuters.com/article/us-nicaragua-violence-idUSKCN24W2Q4",
    scope: "single",
  },
  {
    id: "ghazanchetsots-shushi-2020",
    title: "Shelling of Ghazanchetsots Cathedral",
    siteName: "Holy Savior Cathedral (Ghazanchetsots)",
    occurredOn: "2020-10-08",
    country: "Azerbaijan",
    countryCode: "AZE",
    city: "Shushi / Shusha",
    region: "Middle East & North Africa",
    latitude: 39.7581,
    longitude: 46.7478,
    incidentType: "shelling",
    severity: "high",
    fatalities: 0,
    injured: 3,
    structuresDamaged: 1,
    denomination: "Armenian Apostolic",
    summary:
      "Two successive strikes hit the 19th-century Armenian cathedral in Shushi during the 2020 Nagorno-Karabakh war, collapsing part of the dome. Journalists sheltering inside were wounded.",
    context:
      "Human Rights Watch said the second strike made an accident unlikely. Azerbaijan denied targeting the church. The building later underwent contested reconstruction.",
    sourceName: "Human Rights Watch",
    sourceUrl: "https://www.hrw.org/news/2020/12/16/azerbaijan-attack-church-possible-war-crime",
    scope: "single",
  },
  {
    id: "mocimboa-churches-2020",
    title: "Churches burned in the fall of Mocímboa da Praia",
    siteName: "Parish churches, Mocímboa da Praia",
    occurredOn: "2020-08-12",
    country: "Mozambique",
    countryCode: "MOZ",
    city: "Mocímboa da Praia",
    region: "Sub-Saharan Africa",
    latitude: -11.3496,
    longitude: 40.3511,
    incidentType: "arson",
    severity: "high",
    fatalities: 0,
    injured: 0,
    structuresDamaged: 4,
    denomination: "Catholic and Protestant",
    summary:
      "ISIS-linked militants seized the Cabo Delgado port town and burned churches along with government buildings. Clergy and parishioners fled south.",
    context:
      "The Cabo Delgado insurgency has emptied Christian and Muslim communities alike; churches are routinely burned when towns fall.",
    sourceName: "Aid to the Church in Need / AP",
    sourceUrl: "https://www.churchinneed.org/",
    scope: "campaign",
  },
  {
    id: "morinville-st-jean-2021",
    title: "Arson at St. Jean Baptiste, Morinville",
    siteName: "St. Jean Baptiste Catholic Church",
    occurredOn: "2021-06-30",
    country: "Canada",
    countryCode: "CAN",
    city: "Morinville",
    region: "North America",
    latitude: 53.8021,
    longitude: -113.6496,
    incidentType: "arson",
    severity: "moderate",
    fatalities: 0,
    injured: 0,
    structuresDamaged: 1,
    denomination: "Catholic",
    summary:
      "Fire destroyed a historic wooden parish north of Edmonton. Investigators treated it as arson. It was among more than 60 Canadian churches burned or vandalized after the 2021 residential-school grave announcements.",
    context:
      "The 2021 wave is the largest recorded cluster of anti-church arson in a Western country in this ledger. Most cases remain unsolved.",
    sourceName: "CBC News",
    sourceUrl: "https://www.cbc.ca/news/canada/edmonton/morinville-church-fire-1.6086427",
    scope: "single",
  },
  {
    id: "laguna-woods-2022",
    title: "Shooting at Geneva Presbyterian",
    siteName: "Geneva Presbyterian Church",
    occurredOn: "2022-05-15",
    country: "United States",
    countryCode: "USA",
    city: "Laguna Woods",
    region: "North America",
    latitude: 33.6103,
    longitude: -117.7253,
    incidentType: "shooting",
    severity: "high",
    fatalities: 1,
    injured: 5,
    structuresDamaged: 0,
    denomination: "Presbyterian",
    summary:
      "A gunman chained exits and opened fire on a Taiwanese congregation during lunch after worship. One man was killed and five people wounded. Congregants subdued the attacker.",
    context:
      "Federal prosecutors charged the shooting as a hate crime motivated by political grievance against Taiwan. It is one of the few U.S. church attacks with an explicit transnational motive.",
    sourceName: "Department of Justice",
    sourceUrl: "https://www.justice.gov/usao-cdca/pr/las-vegas-man-charged-hate-crime",
    scope: "single",
  },
  {
    id: "owo-st-francis-2022",
    title: "Pentecost massacre at St. Francis Xavier",
    siteName: "St. Francis Xavier Catholic Church",
    occurredOn: "2022-06-05",
    country: "Nigeria",
    countryCode: "NGA",
    city: "Owo",
    region: "Sub-Saharan Africa",
    latitude: 7.1962,
    longitude: 5.5863,
    incidentType: "shooting",
    severity: "critical",
    fatalities: 41,
    injured: 61,
    structuresDamaged: 1,
    denomination: "Catholic",
    summary:
      "Gunmen attacked a packed Pentecost Sunday Mass in Ondo State with rifles and explosives. The government later confirmed 41 dead and more than 60 wounded. In 2026 a federal court sentenced four men to death for the attack.",
    context:
      "ISWAP was widely blamed. Owo sits outside Nigeria’s usual northern conflict belt, which is why the massacre shocked the southwest.",
    sourceName: "Reuters / BBC",
    sourceUrl: "https://www.reuters.com/world/africa/nigerian-court-sentences-four-death-over-2022-owo-catholic-church-attack-2026-06-03/",
    scope: "single",
  },
  {
    id: "cerocahui-jesuits-2022",
    title: "Jesuit priests killed in Cerocahui church",
    siteName: "St. Francis of Assisi Church",
    occurredOn: "2022-06-20",
    country: "Mexico",
    countryCode: "MEX",
    city: "Cerocahui",
    region: "Latin America",
    latitude: 27.3,
    longitude: -108.05,
    incidentType: "shooting",
    severity: "high",
    fatalities: 2,
    injured: 0,
    structuresDamaged: 0,
    denomination: "Catholic (Jesuit)",
    summary:
      "A local crime boss pursued a wounded man into the parish church and shot dead Jesuit priests Javier Campos Morales and Joaquín César Mora Salazar, who had tried to shelter him.",
    context:
      "The killings drew international condemnation of cartel violence against clergy in the Sierra Tarahumara. Mexico is among the most dangerous countries for Catholic priests in the Americas.",
    sourceName: "Reuters",
    sourceUrl: "https://www.reuters.com/world/americas/two-jesuit-priests-killed-northern-mexico-church-2022-06-21/",
    scope: "single",
  },
  {
    id: "kasindi-drc-2023",
    title: "Bombing at a Kasindi church compound",
    siteName: "Pentecostal church, Kasindi",
    occurredOn: "2023-01-15",
    country: "Democratic Republic of the Congo",
    countryCode: "COD",
    city: "Kasindi",
    region: "Sub-Saharan Africa",
    latitude: 0.05,
    longitude: 29.7,
    incidentType: "bombing",
    severity: "critical",
    fatalities: 17,
    injured: 40,
    structuresDamaged: 1,
    denomination: "Pentecostal",
    summary:
      "An explosive detonated at a Sunday service near the Uganda border in North Kivu. At least 17 people were killed. The Allied Democratic Forces, an ISIS-linked militia, were blamed.",
    context:
      "ADF attacks on civilian and church gatherings have made eastern Congo one of the deadliest theaters for Christians after Nigeria.",
    sourceName: "Reuters",
    sourceUrl: "https://www.reuters.com/world/africa/least-10-killed-bomb-attack-east-congo-church-governor-2023-01-15/",
    scope: "single",
  },
  {
    id: "covenant-nashville-2023",
    title: "Shooting at Covenant School",
    siteName: "Covenant Presbyterian Church / Covenant School",
    occurredOn: "2023-03-27",
    country: "United States",
    countryCode: "USA",
    city: "Nashville",
    region: "North America",
    latitude: 36.1033,
    longitude: -86.825,
    incidentType: "shooting",
    severity: "critical",
    fatalities: 6,
    injured: 1,
    structuresDamaged: 0,
    denomination: "Presbyterian",
    summary:
      "A shooter entered the church-run elementary school and killed three nine-year-old children and three staff members before being stopped by police.",
    context:
      "Covenant is a parish school attached to Covenant Presbyterian Church. The attack reopened the U.S. debate on church-campus security.",
    sourceName: "Metropolitan Nashville Police",
    sourceUrl: "https://www.nashville.gov/departments/police",
    scope: "single",
  },
  {
    id: "manipur-churches-2023",
    title: "Church-destruction campaign in Manipur",
    siteName: "Churches across Manipur",
    occurredOn: "2023-05-03",
    country: "India",
    countryCode: "IND",
    city: "Imphal",
    region: "South Asia",
    latitude: 24.817,
    longitude: 93.9368,
    incidentType: "arson",
    severity: "critical",
    fatalities: 0,
    injured: 0,
    structuresDamaged: 250,
    denomination: "Mostly Kuki Christian",
    summary:
      "Ethnic violence between Meitei and Kuki communities that began in May 2023 razed hundreds of churches — estimates run from about 250 to as many as 500 — along with villages in the hill districts.",
    context:
      "Fatalities from the wider conflict number in the hundreds; this entry records the church-destruction campaign, not every killing. Many congregations still worship in relief camps.",
    sourceName: "Aid to the Church in Need / Indian church tallies",
    sourceUrl: "https://www.churchinneed.org/",
    scope: "campaign",
  },
  {
    id: "odessa-transfiguration-2023",
    title: "Missile strike on Transfiguration Cathedral",
    siteName: "Transfiguration Cathedral",
    occurredOn: "2023-07-23",
    country: "Ukraine",
    countryCode: "UKR",
    city: "Odesa",
    region: "Europe",
    latitude: 46.4833,
    longitude: 30.7411,
    incidentType: "shelling",
    severity: "high",
    fatalities: 1,
    injured: 19,
    structuresDamaged: 1,
    denomination: "Orthodox",
    summary:
      "A Russian missile strike on central Odesa gutted the historic Transfiguration Cathedral, killing one person in the district and injuring 19. The interior and altar were destroyed.",
    context:
      "UNESCO condemned the strike on a World Heritage historic center. This entry is logged as conflict damage to a cathedral, not a sectarian attack.",
    sourceName: "UNESCO / Reuters",
    sourceUrl: "https://www.reuters.com/world/europe/russian-missiles-hit-odesa-cathedral-damaged-2023-07-23/",
    scope: "single",
  },
  {
    id: "jaranwala-2023",
    title: "Mob attacks on churches in Jaranwala",
    siteName: "Churches in Jaranwala",
    occurredOn: "2023-08-16",
    country: "Pakistan",
    countryCode: "PAK",
    city: "Jaranwala",
    region: "South Asia",
    latitude: 31.3333,
    longitude: 73.4333,
    incidentType: "arson",
    severity: "high",
    fatalities: 0,
    injured: 0,
    structuresDamaged: 22,
    denomination: "Catholic and Protestant",
    summary:
      "After a blasphemy accusation against two Christian men, a mob burned at least 22 churches and more than 80 Christian homes in Punjab’s Jaranwala tehsil. No deaths were recorded in the main violence; families fled.",
    context:
      "Police later arrested hundreds. Human-rights groups say Pakistan’s blasphemy law remains a recurring trigger for collective punishment of Christian neighborhoods.",
    sourceName: "BBC / Human Rights Watch",
    sourceUrl: "https://www.bbc.com/news/world-asia-66521112",
    scope: "campaign",
  },
  {
    id: "omdurman-churches-2023",
    title: "Churches destroyed in Omdurman",
    siteName: "Sudan Presbyterian Evangelical and Evangelical churches",
    occurredOn: "2023-11-01",
    country: "Sudan",
    countryCode: "SDN",
    city: "Omdurman",
    region: "Middle East & North Africa",
    latitude: 15.6445,
    longitude: 32.4777,
    incidentType: "demolition",
    severity: "high",
    fatalities: 0,
    injured: 0,
    structuresDamaged: 3,
    denomination: "Presbyterian and Evangelical",
    summary:
      "During the war between the Sudanese Armed Forces and the Rapid Support Forces, several churches and Christian schools in Omdurman were destroyed, looted, or occupied.",
    context:
      "After the army retook parts of the capital in 2025, a Pentecostal church was separately reported bulldozed. Sudanese Christians — already a small minority — have been squeezed by both sides of the war.",
    sourceName: "Christianity Today / Open Doors",
    sourceUrl: "https://www.christianitytoday.com/2023/11/sudan-church-bombing-omdurman-evangelical-episcopal-saf-rsf/",
    scope: "campaign",
  },
  {
    id: "holy-family-gaza-2023",
    title: "Killings at the Holy Family compound",
    siteName: "Holy Family Catholic Parish",
    occurredOn: "2023-12-16",
    country: "Palestine",
    countryCode: "PSE",
    city: "Gaza City",
    region: "Middle East & North Africa",
    latitude: 31.524,
    longitude: 34.444,
    incidentType: "shooting",
    severity: "high",
    fatalities: 2,
    injured: 0,
    structuresDamaged: 1,
    denomination: "Catholic",
    summary:
      "Two women, Nahida Khalil Anton and her daughter Samar, were shot and killed inside the Holy Family parish compound, Gaza’s only Catholic church, where civilians were sheltering.",
    context:
      "The Latin Patriarchate said they were hit by an Israeli sniper; the IDF has disputed accounts of incidents at the compound. The parish later suffered further damage as the war continued.",
    sourceName: "Latin Patriarchate of Jerusalem / Reuters",
    sourceUrl: "https://www.reuters.com/world/middle-east/two-women-killed-gaza-church-latin-patriarchate-says-2023-12-16/",
    scope: "single",
  },
  {
    id: "plateau-christmas-2023",
    title: "Christmas attacks in Plateau State",
    siteName: "Villages and churches, Bokkos and Barkin Ladi",
    occurredOn: "2023-12-24",
    country: "Nigeria",
    countryCode: "NGA",
    city: "Bokkos",
    region: "Sub-Saharan Africa",
    latitude: 9.3,
    longitude: 9.0,
    incidentType: "shooting",
    severity: "critical",
    fatalities: 160,
    injured: 300,
    structuresDamaged: 30,
    denomination: "Mostly Protestant and Catholic",
    summary:
      "Coordinated night raids on Christian farming communities over Christmas 2023 killed more than 140 people in Bokkos and Barkin Ladi — later tallies from church and civil-society sources ran toward 160–200. Homes and churches were burned.",
    context:
      "Plateau’s Middle Belt violence is often described as farmer-herder conflict; church leaders and field investigators report repeated, targeted attacks on Christian villages. Nigeria accounted for about 72 percent of Christians killed worldwide in the Open Doors 2026 reporting year.",
    sourceName: "Reuters / Aid to the Church in Need",
    sourceUrl: "https://www.reuters.com/world/africa/over-100-killed-christmas-eve-attacks-nigeria-2023-12-26/",
    scope: "campaign",
  },
  {
    id: "istanbul-santa-maria-2024",
    title: "Shooting during Mass at Santa Maria",
    siteName: "Santa Maria Church",
    occurredOn: "2024-01-28",
    country: "Turkey",
    countryCode: "TUR",
    city: "Istanbul",
    region: "Middle East & North Africa",
    latitude: 41.0082,
    longitude: 28.9784,
    incidentType: "shooting",
    severity: "high",
    fatalities: 1,
    injured: 1,
    structuresDamaged: 0,
    denomination: "Catholic",
    summary:
      "Two masked gunmen entered Sunday Mass at a Catholic church in Istanbul’s Sarıyer district and killed one worshipper. Islamic State later claimed the attack.",
    context:
      "It was the first fatal ISIS-claimed church shooting in Turkey in years and raised security at the country’s remaining Christian sanctuaries.",
    sourceName: "Reuters",
    sourceUrl: "https://www.reuters.com/world/middle-east/gunmen-open-fire-istanbul-church-one-dead-interior-minister-says-2024-01-28/",
    scope: "single",
  },
  {
    id: "wakeley-good-shepherd-2024",
    title: "Stabbing at Christ the Good Shepherd",
    siteName: "Christ the Good Shepherd Church",
    occurredOn: "2024-04-15",
    country: "Australia",
    countryCode: "AUS",
    city: "Wakeley",
    region: "Oceania",
    latitude: -33.874,
    longitude: 150.91,
    incidentType: "stabbing",
    severity: "high",
    fatalities: 0,
    injured: 5,
    structuresDamaged: 0,
    denomination: "Assyrian Orthodox",
    summary:
      "A 16-year-old attacked Bishop Mar Mari Emmanuel with a knife during a livestreamed Monday service in western Sydney. The bishop and several congregants were wounded. A riot followed outside the church.",
    context:
      "Australian authorities treated the stabbing as a terrorist incident. It is the most serious attack on a church congregation in modern Australian history.",
    sourceName: "ABC News Australia",
    sourceUrl: "https://www.abc.net.au/news/2024-04-15-wakeley-church-stabbing/103711000",
    scope: "single",
  },
  {
    id: "gilet-monastery-2024",
    title: "Attack on Santo Espíritu del Monte",
    siteName: "Monastery of Santo Espíritu del Monte",
    occurredOn: "2024-11-09",
    country: "Spain",
    countryCode: "ESP",
    city: "Gilet",
    region: "Europe",
    latitude: 39.676,
    longitude: -0.321,
    incidentType: "stabbing",
    severity: "high",
    fatalities: 1,
    injured: 7,
    structuresDamaged: 0,
    denomination: "Catholic (Franciscan)",
    summary:
      "A man broke into the Franciscan monastery near Valencia and beat several friars with a stick and a bottle. Brother Juan Antonio Llorente, 76, died two days later from head wounds.",
    context:
      "OIDAC Europe recorded the killing in its 2025 report on anti-Christian hate crime, which also noted a sharp rise in church arson across the continent.",
    sourceName: "Agenzia Fides / CBS",
    sourceUrl: "https://www.cbsnews.com/news/spain-friars-killed-injured-monastery/",
    scope: "single",
  },
  {
    id: "germany-church-arsons-2024",
    title: "Church arson wave in Germany",
    siteName: "Churches across Germany",
    occurredOn: "2024-06-01",
    country: "Germany",
    countryCode: "DEU",
    city: "Berlin",
    region: "Europe",
    latitude: 52.52,
    longitude: 13.405,
    incidentType: "arson",
    severity: "moderate",
    fatalities: 0,
    injured: 0,
    structuresDamaged: 33,
    denomination: "Catholic and Protestant",
    summary:
      "OIDAC Europe recorded 33 arson attacks on German churches in its 2025 reporting year — about a third of all church arsons logged in Europe, and roughly double the previous year’s German total.",
    context:
      "The German bishops’ conference warned that ‘all taboos have been broken’ regarding church vandalism. Most individual cases caused property damage rather than casualties.",
    sourceName: "OIDAC Europe",
    sourceUrl: "https://www.osvnews.com/new-report-notes-significant-rise-in-personal-attacks-on-christians-in-europe/",
    scope: "campaign",
  },
  {
    id: "mar-elias-damascus-2025",
    title: "Suicide bombing at Mar Elias Church",
    siteName: "Mar Elias Greek Orthodox Church",
    occurredOn: "2025-06-22",
    country: "Syria",
    countryCode: "SYR",
    city: "Damascus",
    region: "Middle East & North Africa",
    latitude: 33.5138,
    longitude: 36.2765,
    incidentType: "bombing",
    severity: "critical",
    fatalities: 25,
    injured: 63,
    structuresDamaged: 1,
    denomination: "Greek Orthodox",
    summary:
      "A suicide bomber detonated inside the Greek Orthodox Church of the Prophet Elias in Damascus’s Dweila neighborhood during Sunday liturgy. The Syrian Network for Human Rights recorded 25 civilians killed and 63 wounded; later tallies ran as high as 30 dead.",
    context:
      "It was the deadliest attack on a Damascus church in years and the worst single church massacre logged in this ledger for 2025. Islamic State was widely blamed.",
    sourceName: "Syrian Network for Human Rights / Reuters",
    sourceUrl: "https://www.reuters.com/world/middle-east/blast-rocks-church-syrias-damascus-witnesses-say-2025-06-22/",
    scope: "single",
  },
  {
    id: "early-rain-chengdu-2018",
    title: "Raid on Early Rain Covenant Church",
    siteName: "Early Rain Covenant Church",
    occurredOn: "2018-12-09",
    country: "China",
    countryCode: "CHN",
    city: "Chengdu",
    region: "East & Southeast Asia",
    latitude: 30.5728,
    longitude: 104.0668,
    incidentType: "raid",
    severity: "moderate",
    fatalities: 0,
    injured: 0,
    structuresDamaged: 0,
    denomination: "Unregistered Protestant",
    summary:
      "Police raided one of China’s best-known unregistered congregations, detained Pastor Wang Yi and more than 100 members, and sealed the worship space. Wang was later sentenced to nine years in prison.",
    context:
      "Early Rain became the emblem of the 2018–2019 crackdown on large urban house churches. Similar raids have continued, including a nationwide 2025 operation against Zion Church.",
    sourceName: "Human Rights Watch",
    sourceUrl: "https://www.hrw.org/news/2019/12/12/china-unrelenting-crimes-against-humanity-targeting-religious-groups",
    scope: "single",
  },
  {
    id: "zion-church-china-2025",
    title: "Nationwide raid on Zion Church",
    siteName: "Zion Church congregations",
    occurredOn: "2025-10-10",
    country: "China",
    countryCode: "CHN",
    city: "Beijing",
    region: "East & Southeast Asia",
    latitude: 39.9042,
    longitude: 116.4074,
    incidentType: "raid",
    severity: "moderate",
    fatalities: 0,
    injured: 0,
    structuresDamaged: 0,
    denomination: "Unregistered Protestant",
    summary:
      "Coordinated detentions swept pastors and members of Zion Church, one of China’s largest unregistered networks, in multiple cities. Dozens of leaders were reported held.",
    context:
      "The operation continues a multi-year campaign to force independent congregations into the state-run Three-Self Patriotic Movement or underground.",
    sourceName: "Christianity Today / Open Doors",
    sourceUrl: "https://www.christianitytoday.com/",
    scope: "campaign",
  },
];
